{
    "Message": "Error.",
    "ExceptionMessage": "Error relacionado con la red o específico de la instancia mientras se establecía una conexión con el servidor SQL Server. No se encontró el servidor o éste no estaba accesible. Compruebe que el nombre de la instancia es correcto y que SQL Server está configurado para admitir conexiones remotas. (provider: TCP Provider, error: 0 - El equipo remoto rechazó la conexión de red.)",
    "ExceptionType": "System.Data.SqlClient.SqlException",
    "StackTrace": " en System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)\r\n en System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n en System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n en System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n en System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n en System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n en System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n en System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n en System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n en System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)\r\n en System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)\r\n en System.Data.SqlClient.SqlConnection.Open()\r\n en System.Data.Linq.SqlClient.SqlConnectionManager.UseConnection(IConnectionUser user)\r\n en System.Data.Linq.SqlClient.SqlProvider.Execute(Expression query, QueryInfo queryInfo, IObjectReaderFactory factory, Object[] parentArgs, Object[] userArgs, ICompiledSubQuery[] subQueries, Object lastResult)\r\n en System.Data.Linq.SqlClient.SqlProvider.ExecuteAll(Expression query, QueryInfo[] queryInfos, IObjectReaderFactory factory, Object[] userArguments, ICompiledSubQuery[] subQueries)\r\n en System.Data.Linq.SqlClient.SqlProvider.System.Data.Linq.Provider.IProvider.Execute(Expression query)\r\n en NetSqlAzMan.LINQ.NetSqlAzManStorageDataContext.NetSqlAzMan_DBVersion() en D:\\_vbastidas\\Gd\\Coding\\Membresia\\netsqlazman-75023\\NetSqlAzMan_Solution\\NetSqlAzMan\\LINQ\\NetSqlAzManStorage.designer.cs:línea 651\r\n en NetSqlAzMan.SqlAzManStorage.get_DatabaseVesion() en D:\\_vbastidas\\Gd\\Coding\\Membresia\\netsqlazman-75023\\NetSqlAzMan_Solution\\NetSqlAzMan\\SqlAzManStorage.cs:línea 258\r\n en NetSqlAzMan.CustomBussinessLogic.DBUserBusinessFactory.getStorage() en D:\\_vbastidas\\Gd\\Coding\\Membresia\\netsqlazman-75023\\NetSqlAzMan.CustomBussinessLogic\\DBUserBusinessFactory.cs:línea 16\r\n en NetSqlAzMan.CustomBussinessLogic.DBUserBusinessFactory.<RegisterAsync>d__8.MoveNext() en D:\\_vbastidas\\Gd\\Coding\\Membresia\\netsqlazman-75023\\NetSqlAzMan.CustomBussinessLogic\\DBUserBusinessFactory.cs:línea 164\r\n--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---\r\n en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n en System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n en AzManStructureMgtWebApi.Controllers.DBUserController.<Post>d__2.MoveNext() en D:\\_vbastidas\\Gd\\Coding\\Membresia\\NetSqlAzMan-ServiceExtensions\\AzManStructureMgtWebApi\\Controllers\\DBUserController.cs:línea 63",
    "InnerException": {
        "Message": "Error.",
        "ExceptionMessage": "El equipo remoto rechazó la conexión de red",
        "ExceptionType": "System.ComponentModel.Win32Exception",
        "StackTrace": null
    }
}